export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const GET_MYBRANCHES = 'GET_MYBRANCHES';
export const BRANCH_ERROR = 'BRANCH_ERROR';
export const CLEAR_BRANCHES='CLEAR_BRANCHES'