import React from 'react'
import OwnerNav from '../../../components/nav/OwnerNav'
import './ownerDashBoard.css'

import { Layout } from 'antd'

const { Header, Content, Footer } = Layout

const OwnerDashbord = () => {
	return (
		<>
			<div>
				<Layout style={{ minHeight: '100vh' }}>
					<OwnerNav />
					<Layout className='site-layout' style={{ marginLeft: 200 }}>
						<Header className='site-layout-background' style={{ padding: 0 }} />
						<Content style={{ margin: '24px 16px 0', overflow: 'initial' }}>
							<div
								className='site-layout-background'
								style={{ padding: 24, textAlign: 'center' }}
							>
								...
								<br />
								Really
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								long
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								...
								<br />
								content
							</div>
						</Content>
						<Footer style={{ textAlign: 'center' }}>
							Ant Design ©2018 Created by Ant UED
						</Footer>
					</Layout>
				</Layout>
			</div>
		</>
	)
}

export default OwnerDashbord
